### ISSUE TITLE
angular2-pagination

### ISSUE THREAD

**Issue by ThomsCass** [Urigo/angular2-meteor#236] opened 2016-04-20 08:24 UTC
Hi,

After following the tutorial in number 12 I got this message in the console when I launch the app.

```javascript
Unable to resolve some modules:

  "!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./pagination-controls-cmp.less" in /Users/Thoms/Desktop/dev/meteor/1.3.X/socially/node_modules/angular2-pagination/pagination-controls-cmp.js
(web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save !!.
```
Anyway this doesn't break anything !

**Comment by wintersa** [comment] 2016-04-30 11:25
I experience almost the same as @ThomsCass problem after step 8, building the Socially Tutorial App.         
[https://github.com/Urigo/angular2-meteor-accounts-ui/issues/2 
](url)

It looks like the bug is in the NPM package **angular2-meteor-accounts-ui**
And it does break things, like breaking authentication in the app. The login form** <login-buttons></login-buttons> **is not working. So there is no UI to authenticate. :-)

Anyway, I was curious if members experience the same issues, and share the knowledge with me. For trying to catch the problem myself, I would like to get **.meteor\packages** and **.meteor\versions** shared, it would help me understand my meteor package better. Also the **package.json** and **tsconfig.json** files would help.

**Comment by ThomsCass** [comment] 2016-04-30 11:56
check here #243

**Comment by ThomsCass** [comment] 2016-04-30 12:04
Is the routing working for you?

**Comment by wintersa** [comment] 2016-04-30 13:07
@ThomsCass  I thought about routing, and if that could cause the issue. At the step in tutorial where I landed, the routing is working the as in the tutorial examples. So I cannot figure out if routing is the problem.

But the problem is that the login buttons on the party-details.html page will not load. The error is generated when loading the party-details page. This is the imported class in **party-details..ts**, that is causing the issue;

`import {LoginButtons} from 'angular2-meteor-accounts-ui/login-buttons';`

**Comment by barbatus** [comment] 2016-05-15 10:34
a dup of https://github.com/Urigo/angular2-meteor-accounts-ui/issues/2

**Closed by barbatus** 2016-05-15 10:34 UTC
