### ISSUE TITLE
Errors with Angular2 2.0.0

### ISSUE THREAD

**Issue by gsdomino** [Urigo/angular2-meteor#392] opened 2016-09-16 03:11 UTC
I am getting the following console errors following a new install of Angular2 2.0.0 although the meteor server starts the app.  I am bootstrapping the app per the Angular2 instructions so maybe that is my problem(?). Anyway, below the console errors I have included my package.json file and my app.module.ts file.

_console errors_
VM12347 modules.js?hash=6d9a94d…:10650 Uncaught SyntaxError: Unexpected token export
VM12348 es5-shim.js?hash=22b8e85…:2789Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12348 es5-shim.js?hash=22b8e85…:17(anonymous function) @ VM12348 es5-shim.js?hash=22b8e85…:2789
VM12349 promise.js?hash=2d5b025…:581Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12349 promise.js?hash=2d5b025…:17(anonymous function) @ VM12349 promise.js?hash=2d5b025…:581
VM12350 ecmascript-runtime.js?hash=c3b4c85…:4630Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12350 ecmascript-runtime.js?hash=c3b4c85…:17(anonymous function) @ VM12350 ecmascript-runtime.js?hash=c3b4c85…:4630
VM12351 babel-compiler.js?hash=aa1ba23…:7 Uncaught TypeError: Cannot read property 'Symbol' of undefined(anonymous function) @ VM12351 babel-compiler.js?hash=aa1ba23…:7(anonymous function) @ VM12351 babel-compiler.js?hash=aa1ba23…:17
VM12358 babel-runtime.js?hash=5430340…:1241Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12358 babel-runtime.js?hash=5430340…:17(anonymous function) @ VM12358 babel-runtime.js?hash=5430340…:1241
VM12360 random.js?hash=c487926…:355Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12360 random.js?hash=c487926…:18(anonymous function) @ VM12360 random.js?hash=c487926…:355
VM12361 mongo-id.js?hash=172813d…:19Uncaught TypeError: Cannot read property 'Random' of undefined(anonymous function) @ VM12361 mongo-id.js?hash=172813d…:19(anonymous function) @ VM12361 mongo-id.js?hash=172813d…:142
VM12363 geojson-utils.js?hash=7214728…:439Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12363 geojson-utils.js?hash=7214728…:17(anonymous function) @ VM12363 geojson-utils.js?hash=7214728…:439
VM12364 minimongo.js?hash=88217d6…:3877Uncaught TypeError: Cannot read property 'MongoID' of undefined(anonymous function) @ VM12364 minimongo.js?hash=88217d6…:23(anonymous function) @ VM12364 minimongo.js?hash=88217d6…:3877
VM12365 check.js?hash=bf95dee…:613Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12365 check.js?hash=bf95dee…:17(anonymous function) @ VM12365 check.js?hash=bf95dee…:613
VM12366 retry.js?hash=91c2261…:18Uncaught TypeError: Cannot read property 'Random' of undefined(anonymous function) @ VM12366 retry.js?hash=91c2261…:18(anonymous function) @ VM12366 retry.js?hash=91c2261…:110
VM12367 ddp-common.js?hash=a99cb35…:493Uncaught TypeError: Cannot read property 'check' of undefined(anonymous function) @ VM12367 ddp-common.js?hash=a99cb35…:17(anonymous function) @ VM12367 ddp-common.js?hash=a99cb35…:493
VM12368 reload.js?hash=ad99c3e…:309Uncaught TypeError: Cannot read property 'Symbol' of undefined(anonymous function) @ VM12368 reload.js?hash=ad99c3e…:18(anonymous function) @ VM12368 reload.js?hash=ad99c3e…:309
VM12369 ddp-client.js?hash=2750240…:4983Uncaught TypeError: Cannot read property 'check' of undefined(anonymous function) @ VM12369 ddp-client.js?hash=2750240…:17(anonymous function) @ VM12369 ddp-client.js?hash=2750240…:4983
VM12370 ddp.js?hash=752b775…:7 Uncaught TypeError: Cannot read property 'DDP' of undefined(anonymous function) @ VM12370 ddp.js?hash=752b775…:7(anonymous function) @ VM12370 ddp.js?hash=752b775…:20
VM12372 allow-deny.js?hash=11ff6d1…:18Uncaught TypeError: Cannot read property 'LocalCollection' of undefined(anonymous function) @ VM12372 allow-deny.js?hash=11ff6d1…:18(anonymous function) @ VM12372 allow-deny.js?hash=11ff6d1…:536
VM12374 mongo.js?hash=ed0b13a…:908Uncaught TypeError: Cannot read property 'AllowDeny' of undefined(anonymous function) @ VM12374 mongo.js?hash=ed0b13a…:17(anonymous function) @ VM12374 mongo.js?hash=ed0b13a…:908
VM12376 jquery.js?hash=22a0055…:10421Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12376 jquery.js?hash=22a0055…:17(anonymous function) @ VM12376 jquery.js?hash=22a0055…:10421
VM12381 barbatus_angular2-runtime.js?hash=d933c39…:18Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12381 barbatus_angular2-runtime.js?hash=d933c39…:18(anonymous function) @ VM12381 barbatus_angular2-runtime.js?hash=d933c39…:45
VM12382 xolvio_cleaner.js?hash=24ad985…:17Uncaught TypeError: Cannot read property 'Mongo' of undefined(anonymous function) @ VM12382 xolvio_cleaner.js?hash=24ad985…:17(anonymous function) @ VM12382 xolvio_cleaner.js?hash=24ad985…:102
VM12384 practicalmeteor_chai.js?hash=6b28977…:7 Uncaught TypeError: Cannot read property 'Symbol' of undefined(anonymous function) @ VM12384 practicalmeteor_chai.js?hash=6b28977…:7(anonymous function) @ VM12384 practicalmeteor_chai.js?hash=6b28977…:5629
VM12385 practicalmeteor_sinon.js?hash=d51f09b…:7 Uncaught TypeError: Cannot read property 'chai' of undefined(anonymous function) @ VM12385 practicalmeteor_sinon.js?hash=d51f09b…:7(anonymous function) @ VM12385 practicalmeteor_sinon.js?hash=d51f09b…:6246
VM12386 hwillson_stub-collections.js?hash=2280a4d…:17 Uncaught TypeError: Cannot read property 'Mongo' of undefined(anonymous function) @ VM12386 hwillson_stub-collections.js?hash=2280a4d…:17(anonymous function) @ VM12386 hwillson_stub-collections.js?hash=2280a4d…:103
VM12388 barbatus_angular2-polyfills.js?hash=d23d839…:18 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12388 barbatus_angular2-polyfills.js?hash=d23d839…:18(anonymous function) @ VM12388 barbatus_angular2-polyfills.js?hash=d23d839…:45
VM12389 webapp.js?hash=b74e229…:18 Uncaught TypeError: Cannot read property 'meteorInstall' of undefined(anonymous function) @ VM12389 webapp.js?hash=b74e229…:18(anonymous function) @ VM12389 webapp.js?hash=b74e229…:70
VM12390 livedata.js?hash=e7fb2e7…:7 Uncaught TypeError: Cannot read property 'DDP' of undefined(anonymous function) @ VM12390 livedata.js?hash=e7fb2e7…:7(anonymous function) @ VM12390 livedata.js?hash=e7fb2e7…:24
VM12395 autoupdate.js?hash=cd7c85b…:19 Uncaught TypeError: Cannot read property 'Retry' of undefined(anonymous function) @ VM12395 autoupdate.js?hash=cd7c85b…:19(anonymous function) @ VM12395 autoupdate.js?hash=cd7c85b…:206
VM12397 global-imports.js?hash=599677e…:3 Uncaught TypeError: Cannot read property 'Mongo' of undefined(anonymous function) @ VM12397 global-imports.js?hash=599677e…:3
VM12398 app.js?hash=bfbcba2…:1 Uncaught ReferenceError: meteorInstall is not defined

_package.json__
"name": "angular2-meteor-base",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "meteor test --driver-package practicalmeteor:mocha",
    "test:ci": "meteor test --once --driver-package dispatch:mocha-phantomjs"
  },
  "devDependencies": {
    "chai": "3.5.0",
    "chai-spies": "0.7.1"
  },
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@angular/router": "3.0.0-rc.2",
    "@angular/upgrade": "2.0.0",
    "angular2-meteor": "^0.7.0-beta.1",
    "angular2-meteor-polyfills": "0.1.1",
    "angular2-meteor-tests-polyfills": "0.0.2",
    "core-js": "^2.4.0",
    "es6-shim": "0.35.1",
    "ie-shim": "^0.1.0",
    "meteor-node-stubs": "0.2.3",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.38",
    "zone.js": "~0.6.17"
  }
}

_app.module.ts_
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import {METEOR_PROVIDERS, MeteorReactive } from 'angular2-meteor'; 
[terminal error: client/app.module.ts (3, 27): Module '"node_modules/angular2-meteor/dist/index"' has no exported member 'MeteorReactive']

import { AppComponent }  from './app.component';
//import { DemoComponent } from './imports/demo/demo.component';

import { DemoDataService } from './imports/demo/demo-data.service';

@NgModule({
  imports: [ BrowserModule ],       // module dependencies
  declarations: [ AppComponent ],   // components and directives
  bootstrap: [ AppComponent ],     // root component
  providers: [ METEOR_PROVIDERS, DemoDataService ]                    // services
})
export class AppModule { }

**Comment by Vader699** [comment] 2016-09-16 05:02
Try going into node_modules/angular2-meteor and running npm install.  That worked for me.  I don't think the package is installing correctly.

**Comment by njbuch** [comment] 2016-09-16 06:12
As I understand it, there is still some breaking changes after AG2RC5 that has not been integrated into this module yet.

**Comment by stefanholzapfel** [comment] 2016-09-16 10:04
As njbuch said, angular2-meteor is "officialy" fit for rc4, although it works with RC5 for me. RC6 and Agular 2 Final are not yet supported.

**Comment by PseudoPsycho** [comment] 2016-09-18 10:07
Should be the same problem as #381 - hopefully the responsible angular/angular#11309 will get fixed soon.

**Comment by gsdomino** [comment] 2016-09-18 13:38
Is anyone running with RC-6?

**Comment by neeraj1928** [comment] 2016-09-19 12:56
today I created a new angular2-meteor project. And I am getting this error
`npm ERR! No compatible version found: @angular/forms@=2.0.0-rc.5
npm ERR! Valid install targets:
npm ERR! 2.0.0, 2.0.0-rc.7, 2.0.0-rc.6, 0.3.0, 0.2.0, 0.1.1, 0.1.0
npm ERR! 
`

**Comment by PseudoPsycho** [comment] 2016-09-19 13:07
The version format changed with RC6. It used to have it's own number
before. You will want to use 0.3.0

neeraj <notifications@github.com> schrieb am Mo., 19. Sep. 2016, 14:57:

**Comment by neeraj1928** [comment] 2016-09-19 13:38
now since angular2 is officially been released, when can we expect angular2-meteor to support this final release.

**Comment by PseudoPsycho** [comment] 2016-09-19 13:43
How I understood it, once angular/angular#11309 has been fixed at the earliest. So this is not the responsibility of angular2-meteor's team but Angular's.

**Comment by neeraj1928** [comment] 2016-09-19 13:54
tried but failed

**Comment by donvadicastro** [comment] 2016-09-19 14:38
Does anyone know some workarounds for this problem?

**Comment by gsdomino** [comment] 2016-09-19 15:55
This package.json was for angular2-meteor version "0.7.0-beta.1" was posted here 4 days ago: https://github.com/Urigo/angular2-meteor/blob/master/package.json 
Does this not work?

**Comment by danielleburgess** [comment] 2016-09-19 16:34
Does anyone know when can we expect angular2-meteor to support the final release of angular2??

**Comment by Urigo** [comment] 2016-09-20 00:36
we are working hard on it, probably about a week

**Comment by barbatus** [comment] 2016-09-23 20:27
please try 0.7.0-beta2 with Angular2 2.0.0.

**Comment by mxab** [comment] 2016-09-23 20:31
@barbatus is there a sample project with beta2 ? I tried it but I'm having some zone issues, maybe there is something of with my setup

**Comment by barbatus** [comment] 2016-09-23 20:58
@mxab try to remove ecmascript package and add barbatus:angular2-polyfills.

**Comment by Vader699** [comment] 2016-09-24 06:09
Tried out 0.7.0-beta.2 removing ecmascript package.  App runs until I activate a component that extends MeteorReactive then I get this in the console.

EXCEPTION: Uncaught (in promise): Error: Error in ./SockItComponent class SockItComponent - inline template:0:586 caused by: Cannot extend IterableDiffers without a parent injector

**Comment by mxab** [comment] 2016-09-24 07:55
@barbatus ok this resolved the zone issue now I'm also getting the issue mentioned in https://github.com/angular/angular/issues/11309 . Not sure how I should apply the workarround.

Also I'm not sure is should I use the `angular2-meteor-auto-bootstrap` package or simply include the `MeteorModule` in the App modules `imports: [MeteorModule]` block.

final question, should new angular2-meteor issues be raised in this repo or in the angular-meteor as you merged all the code in the there.

**Comment by barbatus** [comment] 2016-09-24 08:02
@mxab make sure you are using exactly v0.7.0-beta.2, just include METEOR_PROVIDERS in NgModule, bootstrap package is not needed.

**Comment by stefanholzapfel** [comment] 2016-09-24 10:53
I updated to 0.7.0-beta.2 and Angular Version 2.0.1, removed the atmosphere ecmascript package, added barbatus:angular2-polyfills and now I'm also getting this in a child component:

Uncaught Error: Error in ./ToastComponent class ToastComponent - inline template:0:0 caused by: Cannot extend IterableDiffers without a parent injector

METEOR_PROVIDERS was added to my core's providers array

**Comment by barbatus** [comment] 2016-09-24 13:57
@stefanholzapfel since we are moving this repo to angular-meteor, we had some issues with merging. So try 0.7.0-beta.3 which I verified contains the right code now.

**Comment by stefanholzapfel** [comment] 2016-09-24 14:54
Thanks, not it seems to work!!

**Comment by mxab** [comment] 2016-09-24 16:55
same here, works 👍

**Comment by Jitra** [comment] 2016-09-24 19:27
@mxab do you mind placing here your package.json and meteor module list so that I can create project myself?

Trying to run meteor from the [meteor-boilerplate](https://github.com/bsliran/angular2-meteor-base)
with angular2 meteor 0.7.0-beta.3 and still see the error from the first comment

**Comment by Vader699** [comment] 2016-09-24 22:24
0.7.0-beta.3 is working for me as well. Also did a meteor build and that is also working fine.

**Comment by mxab** [comment] 2016-09-25 01:17
@Jitra 
*package.json*
```
{
  "name": "my-project",
  "private": true,
  ,
  "dependencies": {
    "@angular/common": "2.0.1",
    "@angular/compiler": "2.0.1",
    "@angular/core": "2.0.1",
    "@angular/forms": "2.0.1",
    "@angular/http": "2.0.1",
    "@angular/platform-browser": "2.0.1",
    "@angular/platform-browser-dynamic": "2.0.1",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.1",
    "angular2-meteor": "0.7.0-beta.3",
    "angular2-meteor-accounts-ui": "^0.6.0",
    "angular2-meteor-polyfills": "^0.1.1",
    "angular2-moment": "^0.8.1",
    "bcrypt": "^0.8.7",
    "core-js": "^2.4.1",
    "es6-shim": "0.35.1",
    "lodash": "4.14.0",
    "meteor-node-stubs": "0.2.3",
    "moment": "2.14.1",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.23"
  }
}
```
*.meteor/packages*:

```
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12                   # The database Meteor supports right now
reactive-var@1.0.10            # Reactive variable for tracker
jquery@1.11.9                  # Helpful client-side library
tracker@1.1.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.2.0   # CSS minifier run for production mode
standard-minifier-js@1.2.0    # JS minifier run for production mode
es5-shim@4.6.14                # ECMAScript 5 compatibility for older browsers.

barbatus:angular2-polyfills
angular2-compilers
barbatus:angular2-runtime
...

email@1.1.17
check@1.2.3
http@1.2.9
shell-server
```
*app.module.ts*:
```
@NgModule({
...
providers : [METEOR_PROVIDERS, ... ]
...
```

*bootstrap.ts*
```
import 'reflect-metadata'; // not tested if necessary
import 'zone.js';  // not tested if necessary
....
platformBrowserDynamic().bootstrapModule(AppModule)
...
```

**Comment by derek-fong** [comment] 2016-09-25 09:14
Tested and confirmed `angular2-meteor@0.7.0-beta.3` works with `@angular@2.0.1`. 

I have created a simple app [here](https://github.com/derek-fong/angular2-meteor-boilerplate) if anyone wants to test out the new versions.

**Comment by Jitra** [comment] 2016-09-26 18:04
@barbatus
Followed the config described by @mxab and still see the error from the first comment.
I saw that @derek-fong managed to use MeteorReactive on the Service in his [repo](https://github.com/derek-fong/angular2-meteor-boilerplate)  but, when I use it on the component like in the README i see the error from the first comment as well.


class looks like below 
```
@Component({
  styles: [style],
  template
})
export class DemoListComponent extends MeteorReactive implements OnInit {
  private demoItems$: Observable<DemoItem[]>;
  private showAddItemForm: boolean = false;

  constructor (private demoService: DemoService) {
    super();
  }

  ngOnInit(): void {
    this.demoItems$ = this.demoService.allDemos$.zone();
  }
 (...)
}
```

and at the root module
```
@NgModule({
  imports: [
    appRouting,
    BrowserModule,
    DemoModule,
  ],
  providers: [METEOR_PROVIDERS],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {}
```


Maybe I am too newbie for all of this..

Hope you'll find this useful for reference thanks for your time in advence

**Comment by barbatus** [comment] 2016-09-26 21:19
@Jitra that only can mean that you are still using other version than angular2-meteor@0.7.0-beta.3. This error is impossible in angular2-meteor@0.7.0-beta.3.

**Comment by Jitra** [comment] 2016-09-26 21:53
Tried to download and install repo again... boom.

Now it works :dancer: 


Forgive me.

**Closed** 2016-09-27 16:13 UTC

**Comment by cubitworx** [comment] 2016-09-28 09:26
For anyone reaching this point and it still not working. I found that I had to delete my `node_modules` directory and rerun `npm install`, in order to get rid of legacy code. For good measure I also did a `meteor reset`. I then had a few new issues to resolve, but once those were resolved everything worked just fine. This from using [derek-fong's repo](https://github.com/derek-fong/angular2-meteor-boilerplate) as a starting point

**Comment by derek-fong** [comment] 2016-09-28 09:32
@cubitworx Be advised `meteor reset` would also clear your app's mongoDB - Please proceed with caution.

**Comment by lekev** [comment] 2016-09-28 15:42
For those who didn't succeed to fix this error, check if your you don't have imported the index file. 
`import {MeteorComponent} from 'angular2-meteor/dist/index'` ==>`import {MeteorComponent} from 'angular2-meteor'`
In the old version of angular2-meteor my IDE choose the index instead of the node-module main file .

**Comment by stefanholzapfel** [comment] 2016-09-28 16:01
I suppose MeteorComponent is deprecated and MeteorReactive should be used instead.
@barbatus is that correct?

**Comment by barbatus** [comment] 2016-09-28 21:15
@stefanholzapfel yes, though MeteorComponent is still there and will be for a while.
