### ISSUE TITLE
type error after upgrade to angular2-meteor 0.5.3

### ISSUE THREAD

**Issue by shalaby** [Urigo/angular2-meteor#238] opened 2016-04-21 08:56 UTC
after upgrade I have this in the console:
`
modules.js?hash=5c54389…:62088 Uncaught TypeError: Cannot read property 'resolve' of undefinedPromiseWrapper.resolve @ modules.js?hash=5c54389…:62088meteorInstall.node_modules.angular2.src.router.route_registry.js @ modules.js?hash=5c54389…:62891fileEvaluate @ modules-runtime.js?hash=939c79d…:158require @ modules-runtime.js?hash=939c79d…:92meteorInstall.node_modules.angular2.src.router.router.js @ modules.js?hash=5c54389…:62334fileEvaluate @ modules-runtime.js?hash=939c79d…:158require @ modules-runtime.js?hash=939c79d…:92meteorInstall.node_modules.angular2.router.js @ modules.js?hash=5c54389…:80592fileEvaluate @ modules-runtime.js?hash=939c79d…:158require @ modules-runtime.js?hash=939c79d…:92meteorInstall.client.components.client-details.client-details.ts @ client-details.ts:4fileEvaluate @ modules-runtime.js?hash=939c79d…:158require @ modules-runtime.js?hash=939c79d…:92(anonymous function) @ transactions.ts:24
`

**Comment by barbatus** [comment] 2016-04-21 09:10
Verify that you have all deps https://github.com/Urigo/angular2-meteor/blob/master/package.json#L29  installed

**Comment by shalaby** [comment] 2016-04-21 09:12
Thanks Alex for your fast response.
Yes I have all the deps and everything was working before the update.

**Comment by shalaby** [comment] 2016-04-21 09:16
<img width="711" alt="localhost 3000 google chrome today at 12 14 53 pm" src="https://cloud.githubusercontent.com/assets/149119/14703882/dbfd917c-07ba-11e6-90b3-ef1bee75eccd.png">
this is more readable.

**Comment by barbatus** [comment] 2016-04-21 09:44
I just checked it works fine with my demos; pls provide a repo to reproduce

**Comment by youngboy** [comment] 2016-04-21 11:05
I am getting exact the same error and trace stack as above, must something wrong in import from router module.

Just created a simple repo to reproduce it

https://github.com/youngboy/typeerror

@barbatus can you check that ? thanks

**Comment by youngboy** [comment] 2016-04-21 15:22
Just made the app works now... ok, I find it purely just by luck, still not sure what is the root reason.
before:
```
import {Component} from 'angular2/core';
import {ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from 'angular2/router';
import {bootstrap} from 'angular2-meteor-auto-bootstrap';
```

after:
```
import {Component} from 'angular2/core';
import {bootstrap} from 'angular2-meteor-auto-bootstrap';
import {ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from 'angular2/router';
```

------

I just move the line of router import at bottom .. 
the exceptions is fire when `angular2/router` module is trying to use `Promise.resove`, but found that `Promise` is undefined

**Comment by shalaby** [comment] 2016-04-21 17:12
Thanks @youngboy for sharing the answer, but now I have this error:
`
=> Errors prevented startup:

   While processing files with barbatus:typescript (for target web.browser):

   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/ts-utils.js:91:65:
   Cannot read property 'code' of undefined
   at
   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/ts-utils.js:91:65
   at Function.findIndex
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/node_modules/underscore/underscore.js:620:13)
   at TsDiagnostics.TDP.hasUnresolvedModules
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/ts-utils.js:89:17)
   at
   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:209:16
   at Cache.CCp.get
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/cache.js:158:19)
   at TSBuild.BP.emit
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:192:23)
   at packages/barbatus:typescript-compiler/typescript-compiler.js:85:30
   at Array.forEach (native)
   at packages/barbatus:typescript-compiler/typescript-compiler.js:65:17
   at
   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
   at
   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:234:13
   at _arrayEach
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:85:13)
   at _each
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:76:13)
   at Object.async.forEachOf.async.eachOf
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:233:9)
   at Object.async.forEach.async.each
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:210:22)
   at TypeScriptCompiler.processFilesForTarget
   (packages/barbatus:typescript-compiler/typescript-compiler.js:56:11)


   While processing files with barbatus:typescript (for target os.osx.x86_64):

   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/ts-utils.js:91:65:
   Cannot read property 'code' of undefined
   at
   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/ts-utils.js:91:65
   at Function.findIndex
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/node_modules/underscore/underscore.js:620:13)
   at TsDiagnostics.TDP.hasUnresolvedModules
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/ts-utils.js:89:17)
   at
   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:209:16
   at Cache.CCp.get
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/cache.js:158:19)
   at TSBuild.BP.emit
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:192:23)
   at packages/barbatus:typescript-compiler/typescript-compiler.js:85:30
   at Array.forEach (native)
   at packages/barbatus:typescript-compiler/typescript-compiler.js:65:17
   at
   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
   at
   /Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:234:13
   at _arrayEach
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:85:13)
   at _each
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:76:13)
   at Object.async.forEachOf.async.eachOf
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:233:9)
   at Object.async.forEach.async.each
   (/Users/medo/.meteor/packages/barbatus_typescript/.0.2.9.1ujdvia++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:210:22)
   at TypeScriptCompiler.processFilesForTarget
   (packages/barbatus:typescript-compiler/typescript-compiler.js:56:11)


=> Your application has errors. Waiting for file change.
`

**Comment by barbatus** [comment] 2016-04-21 18:55
@shalaby pls update to the latest barbatus:typescript

**Comment by orlaqp** [comment] 2016-04-21 19:55
Guys thanks for sharing!! @youngboy your suggestion did work! I was fighting this since last night! Thank you very much guys!!

**Comment by portah** [comment] 2016-04-21 23:11
Hi,
I have the same error, but I created (based on @youngboy repo ) a repo which reproduce the error:
https://github.com/portah/angular2-meteor-promise

I tried almost all combination of packages including the latest:


// barbatus:typescript           upgraded from 0.2.8 to 0.2.10
// barbatus:typescript-compiler  upgraded from 0.5.5 to 0.5.7

**Comment by portah** [comment] 2016-04-21 23:38
If I upgrade everything to the latest version 
```
meteor update
npm install/update
```

and replace just 2 packages with old versions: "angular2-meteor@0.5.2", "angular2-meteor-auto-bootstrap@0.5.1" - everything works again.

**Comment by barbatus** [comment] 2016-04-22 00:24
ok, found the reason, will be fixed soon

**Closed** 2016-04-22 10:43 UTC
Labels: In Progress
