### ISSUE TITLE
Support for Babel instead of TypeScript

### ISSUE THREAD

**Issue by aaronroberson** [Urigo/angular2-meteor#45] opened 2015-12-20 00:32 UTC
I'm on Step 0 of the Angular 2 Socially tutorial but am wanting to use Babel instead of TypeScript.

Thus far I've tried naming my file (app.js) with a .jsx extension like the [readme suggests](https://github.com/Urigo/Meteor-Angular2#import-angular2-into-your-app) but I get an error stating that babel is not defined:

```
 While processing files with barbatus:angular2 (for target web.browser):
   compilers/jsx_compiler.js:19:14: Babel is not defined
```

I tried installing [pbatowski:angular-babel](https://github.com/pbastowski/angular-meteor-babel) and changing my file extension back too `.js` but I get an error in the browser saying `require is not defined.` I'm not actually using `require` anywhere in my code but I do see a `require` function defined in the meteor.d.ts` but I don't suspect it as the problem. Nonetheless, I removed the `typings` directory, rebuilt and not only did the typings get added right back but now I'm getting another error:

```
 While loading plugin `compileNGScript` from package `pbastowski:angular-babel`:
   native: Unexpected token '
   at Object.parse (native)
   at getCustomConfig (packages/compileNGScript/plugin/ng-script-compiler.js:147:1)
```

The entirety of my app.(js/jsx) file is:
```
import {Component, View} from 'angular2/core';
import {bootstrap} from 'angular2/bootstrap';

@Component({
  selector: 'app'
})
@View({
  template: 'Hello World!'
})
class Socially { }

bootstrap(Socially);
```

My index.html file contains:
```
<body>
  <app></app>
  <script>System.import('client/app');</script>
</body>
```

When I was using the angular-meteor-babel package I had a babel.json config in the root with the following settings:
```
{
  "verbose": true,
  "debug": false,
  "modules": "system",
  "blacklist": ['useStrict'],
  "stage": 0,
  "extensions": ["js"]
}
```

Is Babel currently only supported for React and not actually in place of TypeScript? With the correct Babel plugins and presets I don't see any reason why I wouldn't be able to use Babel instead of TypeScript and forego the unwanted typing (sorry I prefer duck typing over cluttering up my source code with type definitions, interfaces, etc. -- personal preference, and reason I write JavaScript and not Java).

**Comment by Urigo** [comment] 2016-02-01 02:05
Duplicate of https://github.com/Urigo/angular2-meteor/issues/32

**Closed by Urigo** 2016-02-01 02:05 UTC
