### ISSUE TITLE
Meteor 1.3 + TypeScript + Imports from Atmosphere marked as error

### ISSUE THREAD

**Issue by dotansimha** [Urigo/angular2-meteor#133] opened 2016-02-06 15:37 UTC
Tracking this issue: https://github.com/meteor/meteor/issues/6177

**Comment by barbatus** [comment] 2016-03-24 12:03
dupe of https://github.com/Urigo/angular2-meteor/issues/144

**Closed by barbatus** 2016-03-24 12:03 UTC
Labels: branch: feature/meteor1.3, component: build:npm, component: build:typescript
