### ISSUE TITLE
0.6.5 compilers error Cordova iOS

### ISSUE THREAD

**Issue by mmazloum** [Urigo/angular2-meteor#430] opened 2016-10-30 18:12 UTC
Hi,

This compilation may be linked to #429 but i'm not sure so here is another report.

with the meteor whatsapp ionic2 example i rebuilt one of my projects. In meteor 1.4.1.3 patch I had no compilation errors but the app didn't launch in the iOS 10 simulator.

So I tryed an update to Meteor 1.4.2 with and without all packages updates and got those compilation errors (web ok, iOS ko, Android not tried : 

>    While processing files with angular2-compilers (for target web.browser):
>    /tools/isobuild/compiler-plugin.js:717:15: 'data' option to addAsset must be a Buffer or String.
>    at ResourceSlot.addAsset (/tools/isobuild/compiler-plugin.js:717:15)
>    at InputFile.addAsset (/tools/isobuild/compiler-plugin.js:482:24)
>    at SassCompilerExtended.addCompileResult (packages/barbatus:css-compiler/compilers/basic_compiler.js:32:15)
>    at packages/caching-compiler/multi-file-caching-compiler.js:144:14
>    at packages/caching-compiler/multi-file-caching-compiler.js:97:11
>    at
>    /Users/marwanmazloum/.meteor/packages/angular2-compilers/.0.6.5.1namkh7++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
>    at replenish
>    (/Users/marwanmazloum/.meteor/packages/angular2-compilers/.0.6.5.1namkh7++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
>    at

**Comment by dotansimha** [comment] 2016-10-31 16:33
@mmazloum , Did you try to `meteor reset` and run again? 
Also, can you share your `.meteor/versions` file?

**Comment by mmazloum** [comment] 2016-10-31 20:07
yes I tried doing meteor reset Here is what is displayed after meteor update : 

callalawyer-app: updated to Meteor 1.4.2.     

Changes to your project's package version selections from updating package versions:

angular2-compilers            upgraded from 0.6.1 to 0.6.5
barbatus:css-compiler         upgraded from 0.3.0 to 0.3.4
barbatus:scss-compiler        upgraded from 3.8.1_1 to 3.8.2
barbatus:typescript           upgraded from 0.4.1 to 0.5.2
barbatus:typescript-compiler  upgraded from 0.7.1_1 to 0.8.4
ddp-common                    upgraded from 1.2.6 to 1.2.7
hwillson:stub-collections     upgraded from 1.0.1 to 1.0.2
minifier-css                  upgraded from 1.2.14_1 to 1.2.15
mobile-status-bar             upgraded from 1.0.12 to 1.0.13
observe-sequence              upgraded from 1.0.12 to 1.0.14
reload                        upgraded from 1.1.10 to 1.1.11
retry                         upgraded from 1.0.8 to 1.0.9
url                           upgraded from 1.0.10 to 1.0.11

Newer versions of the following indirect dependencies are available:
- autoupdate 1.2.11 (1.3.12 is available)  
- caching-compiler 1.0.6 (1.1.8 is available)
- caching-html-compiler 1.0.6 (1.0.7 is available)
- coffeescript 1.1.4 (1.11.1_2 is available) 
- ddp-client 1.2.9 (1.3.2 is available)  
- ddp-server 1.2.10 (1.3.11 is available)  
- http 1.1.8 (1.2.10 is available)  
- launch-screen 1.0.12 (1.1.0 is available)  
- templating 1.1.14 (1.2.15 is available)  

here are my versions : 

accounts-base@1.2.14
accounts-password@1.3.1
allow-deny@1.0.5
angular2-compilers@0.6.5
autoupdate@1.2.11
babel-compiler@6.13.0
babel-runtime@0.1.12
barbatus:css-compiler@0.3.4
barbatus:scss-compiler@3.8.2
barbatus:typescript@0.5.2
barbatus:typescript-compiler@0.8.4
barbatus:typescript-runtime@0.1.2
base64@1.0.10
binary-heap@1.0.10
blaze@2.1.9
blaze-tools@1.0.10
boilerplate-generator@1.0.11
caching-compiler@1.0.6
caching-html-compiler@1.0.6
callback-hook@1.0.10
check@1.2.4
coffeescript@1.1.4
ddp@1.2.5
ddp-client@1.2.9
ddp-common@1.2.7
ddp-rate-limiter@1.0.6
ddp-server@1.2.10
deps@1.0.12
diff-sequence@1.0.7
dispatch:mocha-phantomjs@0.1.7
dispatch:phantomjs-tests@0.0.5
ecmascript@0.5.9
ecmascript-runtime@0.3.15
ejson@1.0.13
email@1.1.18
es5-shim@4.6.15
fastclick@1.0.13
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.1.8
hwillson:stub-collections@1.0.2
id-map@1.0.9
jquery@1.11.10
launch-screen@1.0.12
livedata@1.0.18
localstorage@1.0.12
logging@1.1.16
meteor@1.6.0
meteor-base@1.0.4
minifier-css@1.2.15
minifier-js@1.2.15
minimongo@1.0.18
mobile-experience@1.0.4
mobile-status-bar@1.0.13
modules@0.7.7
modules-runtime@0.7.7
mongo@1.1.14
mongo-id@1.0.6
mys:fonts@0.0.2
npm-bcrypt@0.9.2
npm-mongo@2.2.11_2
observe-sequence@1.0.14
ordered-dict@1.0.9
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
practicalmeteor:mocha@2.4.5_6
practicalmeteor:mocha-core@1.0.1
practicalmeteor:sinon@1.14.1_2
promise@0.8.8
random@1.0.10
rate-limit@1.0.6
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
reywood:publish-composite@1.4.2
routepolicy@1.0.12
service-configuration@1.0.11
sha@1.0.9
shell-server@0.2.1
spacebars@1.0.13
spacebars-compiler@1.0.13
srp@1.0.10
standard-minifier-css@1.3.2
standard-minifier-js@1.2.1
templating@1.1.14
templating-tools@1.0.5
tmeasday:test-reporter-helpers@0.2.1
tracker@1.1.1
ui@1.0.12
underscore@1.0.10
urigo:static-html-compiler@0.1.8
url@1.0.11
webapp@1.3.12
webapp-hashing@1.0.9
xolvio:cleaner@0.3.1

**Comment by dotansimha** [comment] 2016-11-02 11:43
@mmazloum can you share you entire project in a repository? I don't have a way to reproduce the issue without it.

**Comment by kevinhattam** [comment] 2016-11-02 12:41
Hi,

I'm experiencing the same issue on one of my apps. To test I've just ran meteor build on the angular2-meteor-base and I get the same error. Are you able to reproduce this?

> Errors prevented bundling:  
> While processing files with angular2-compilers (for target web.browser):
> /tools/isobuild/compiler-plugin.js:717:15: 'data' option to addAsset must be a Buffer or String.
> at ResourceSlot.addAsset (/tools/isobuild/compiler-plugin.js:717:15)
> at InputFile.addAsset (/tools/isobuild/compiler-plugin.js:482:24)
> at SassCompilerExtended.addCompileResult (packages/barbatus:css-compiler/compilers/basic_compiler.js:32:15)
> at packages/caching-compiler/multi-file-caching-compiler.js:144:14
> at packages/caching-compiler/multi-file-caching-compiler.js:97:11
> at
> /home/kevinhattam/.meteor/packages/angular2-compilers/.0.6.4.1g1b948++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:182:20
> at replenish
> (/home/kevinhattam/.meteor/packages/angular2-compilers/.0.6.4.1g1b948++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:317:21)
> at
> /home/kevinhattam/.meteor/packages/angular2-compilers/.0.6.4.1g1b948++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:328:15
> at Object.async.forEachLimit.async.eachLimit
> (/home/kevinhattam/.meteor/packages/angular2-compilers/.0.6.4.1g1b948++os+web.browser+web.cordova/plugin.Angular2Compilers.os/npm/node_modules/meteor/caching-compiler/node_modules/async/lib/async.js:221:35)
> at SassCompilerExtended.processFilesForTarget (packages/caching-compiler/multi-file-caching-compiler.js:95:11)
> at _loop (packages/barbatus:css-compiler/compilers/style_compiler.js:20:26)
> at StyleCompiler.processFilesForTarget (packages/barbatus:css-compiler/compilers/style_compiler.js:18:36)

I'm running Meteor 1.4.2.
I've tried updating meteor which updates the following -
`angular2-compilers     upgraded from 0.6.4 to 0.6.5`
`babel-runtime          upgraded from 0.1.12 to 0.1.13`
`barbatus:css-compiler  upgraded from 0.3.3 to 0.3.4`

I'm currently unable to build and deploy my app any help would be appreciated.

**Comment by mmazloum** [comment] 2016-11-02 13:03
@dotansimha i'll create a Branch with the problem on my project and add you. If you prefer another repository or if you want to chat feel free to use the gamil provided on my profile.

**Comment by dotansimha** [comment] 2016-11-02 13:33
@barbatus do you have an idea? it looks like something with the compilers

**Comment by mmazloum** [comment] 2016-11-02 14:20
@dotansimha you must have received an invite on a repo with the bug on the branch call-meteor-latest, feel free to contact me on gmail or skype if you have questions.
https://github.com/mmazloum/callalawyer-front/tree/call-meteor-latest

**Comment by barbatus** [comment] 2016-11-02 16:36
pls check if you have empty sass files
do you have the same issue on web?

**Comment by dotansimha** [comment] 2016-11-02 17:04
As @barbatus said, it caused by an empty file. in you case: `client/imports/app/app.component.scss`.
@mmazloum, Note that empty definitions inside a file (for example, just: `span {  }`) is also treated as empty file.
So either remove the empty file or add style definitions to it.
Just verified it with your project and it works fine. 

I am closing this issue, and we will check for a solution in the compilers package.

**Closed as completed by dotansimha** 2016-11-02 17:04 UTC

**Comment by mmazloum** [comment] 2016-11-02 17:44
in deed I've seen it, thanks a lot

**Comment by ayazhussein** [comment] 2016-11-07 21:24
I'm having this problem even without any scss/css files.

**Comment by axlneo** [comment] 2016-11-28 22:05
right !!! thanks
